const composerSelectors = [
  "[data-testid='prompt-textarea']",
  "#prompt-textarea",
  "form textarea",
  "main textarea",
  "form [contenteditable='true'][role='textbox']",
  "main [contenteditable='true'][role='textbox']",
] as const;

export const ChatGPTSelectors = {
  composer: composerSelectors,
  composerDisabled: composerSelectors.flatMap((selector) => [
    `${selector}[disabled]`,
    `${selector}[aria-disabled='true']`,
  ]),
  stopGeneratingButton: [
    "button[data-testid='stop-button']",
    "button[data-testid='stop-response-button']",
    "button[aria-label*='Stop generating' i]",
    "button[aria-label*='Stop response' i]",
    "button[aria-label*='停止生成']",
    "button[aria-label*='停止响应']",
  ],
  ariaBusy: ["[aria-busy='true']"],
  sendButton: [
    "button[data-testid='send-button']",
    "button[aria-label='Send prompt']",
    "button[aria-label='Send message']",
    "button[aria-label='发送提示']",
    "button[aria-label='发送消息']",
    "form button[type='submit']",
  ],
  loginControls: [
    "a[href*='/auth/login']",
    "button[data-testid='login-button']",
    "button[aria-label*='Log in']",
    "a[href*='login']",
  ],
  projectLinks: [
    "nav a[href*='/g/g-p-']",
    "aside a[href*='/g/g-p-']",
    "a[href*='/project']",
    "nav a",
    "aside a",
  ],
  conversationLinks: [
    "nav a[href*='/c/']",
    "aside a[href*='/c/']",
    "a[href*='/c/']",
  ],
  newConversation: [
    "a[data-testid='create-new-chat-button']",
    "button[data-testid='create-new-chat-button']",
    "a[href='/']",
    "button[aria-label='New chat']",
    "button[aria-label='新聊天']",
    "nav a[aria-label*='chat']",
  ],
  conversationMenuButton: [
    "button[data-testid='conversation-options-button']",
    "button[data-testid*='conversation'][data-testid*='option']",
    "button[data-testid*='history-item'][data-testid*='option']",
    "button[data-testid$='-options']",
    "button[aria-label='Open conversation options']",
    "button[aria-label='打开对话选项']",
    "button[aria-label*='conversation options' i]",
    "button[aria-label*='chat options' i]",
    "button[aria-label*='对话选项']",
    "button[aria-label*='聊天选项']",
    "button[aria-haspopup='menu']",
  ],
  currentConversationMenuButton: [
    "header button[data-testid='conversation-options-button']",
    "main button[data-testid='conversation-options-button']",
    "header button[aria-label*='conversation options' i]",
    "header button[aria-label*='chat options' i]",
    "header button[aria-label*='对话选项']",
    "header button[aria-label*='聊天选项']",
  ],
  menuItems: [
    "[role='menuitem'][data-testid*='rename' i]",
    "[role='menuitem'][aria-label*='rename' i]",
    "[role='menuitem'][aria-label*='重命名']",
    "[role='menu'] [role='menuitem']",
    "[data-radix-menu-content] [role='menuitem']",
    "[role='menuitem']",
  ],
  renameInput: [
    "input[data-testid='rename-conversation-input']",
    "input[data-testid*='rename' i]",
    "input[aria-label*='rename' i]",
    "input[aria-label*='重命名']",
    "[role='dialog'] input",
    "input[placeholder*='name' i]",
    "input[placeholder*='名称']",
  ],
  renameConfirmButton: [
    "[role='dialog'] button[data-testid='confirm-button']",
    "[role='dialog'] button[type='submit']",
    "button[data-testid*='rename'][data-testid*='confirm']",
    "button[data-testid='confirm-button']",
  ],
  currentConversationTitle: [
    "[data-testid='conversation-title']",
    "[data-testid*='conversation-title']",
    "header h1",
    "header h2",
  ],
  userMessages: [
    "[data-message-author-role='user']",
    "[data-testid^='conversation-turn-'] [data-message-author-role='user']",
    "article[data-turn='user']",
  ],
  assistantMessages: [
    "[data-message-author-role='assistant']",
    "article[data-turn='assistant']",
    "[data-testid^='conversation-turn-'][data-turn='assistant']",
  ],
  assistantMessageBody: [
    ".markdown",
    ".prose",
    "[class*='markdown']",
  ],
  pageReadyRoot: ["main", "[role='main']", "body"],
} as const;
